Rails:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 125
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 20
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
